#ifndef _NSL_KERNEL_H
#define _NSL_KERNEL_H

#include "nsl_3_layer.h"
#include "nsl_4_layer.h"
#include "nsl_base.h"
#include "nsl_base_list.h"
#include "nsl_cmd_buf.h"
#include "nsl_cmd_data_layer.h"
#include "nsl_cmd_diff.h"
#include "nsl_cmd_exec_assign.h"
#include "nsl_cmd_exec_cd.h"
#include "nsl_cmd_exec_close.h"
#include "nsl_cmd_exec_connect.h"
#include "nsl_cmd_exec_cont.h"
#include "nsl_cmd_exec_csh.h"
#include "nsl_cmd_exec_disable.h"
#include "nsl_cmd_exec_elem.h"
#include "nsl_cmd_exec_enable.h"
#include "nsl_cmd_exec_exec.h"
#include "nsl_cmd_exec_file_disable.h"
#include "nsl_cmd_exec_file_enable.h"
#include "nsl_cmd_exec_help.h"
#include "nsl_cmd_exec_init.h"
#include "nsl_cmd_exec_load.h"
#include "nsl_cmd_exec_open.h"
#include "nsl_cmd_exec_print.h"
#include "nsl_cmd_exec_run.h"
#include "nsl_cmd_exec_set.h"
#include "nsl_cmd_exec_stop.h"
#include "nsl_cmd_macro.h"
#include "nsl_cmd_system.h"
#include "nsl_diff_euler_data.h"
#include "nsl_diff_euler_matrix.h"
#include "nsl_diff_euler_vector.h"
#include "nsl_diff_interpolation_data.h"
#include "nsl_diff_interpolation_vector.h"
#include "nsl_diff_interpolation_matrix.h"
#include "nsl_error.h"
#include "nsl_int_data.h"
#include "nsl_interpreter.h"
#include "nsl_layer.h"
#include "nsl_matrix_layer.h"
#include "nsl_model.h"
#include "nsl_num.h"
#include "nsl_num_4.h"
#include "nsl_num_data.h"
#include "nsl_num_matrix.h"
#include "nsl_num_vector.h"
#include "nsl_on_off_data.h"
#include "nsl_row_col_data.h"
#include "nsl_system.h"




#endif
