# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = qtnsl

QT = core gui widgets qml printsupport
CONFIG += static
Release: DESTDIR = $$PWD/bin/release
Debug:   DESTDIR = $$PWD/bin/debug

HEADERS = \
   $$PWD/NSLControls/incl/NSLMainWindow.h \
   $$PWD/NSLControls/incl/NSLVectorGraph.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_block_stim.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_block_stim_data.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_block_stim_matrix.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_block_stim_vector.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_icon_stim.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_icon_stim_data.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_icon_stim_matrix.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_icon_stim_vector.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_input_data.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_input_include.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_input_layer.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_input_matrix.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_input_vector.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_spec_type.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_stim.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_stim_data.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_stim_matrix.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_stim_type.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_stim_vector.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_cmd_time_interval.h \
   $$PWD/NSLfiles/input/incl/cmd_stim_incl/nsl_input_include.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_block_stim_data.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_block_stim_matrix.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_block_stim_vector.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_icon_stim_data.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_icon_stim_matrix.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_icon_stim_vector.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_input_data.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_input_layer.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_input_matrix.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_input_vector.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_stim.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_stim_data.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_stim_matrix.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_stim_vector.h \
   $$PWD/NSLfiles/input/incl/input_stim_incl/nsl_time_interval.h \
   $$PWD/NSLfiles/input/incl/nsl_all_input_include.h \
   $$PWD/NSLfiles/input/incl/nsl_cmd_input_include.h \
   $$PWD/NSLfiles/input/incl/nsl_command_include.h \
   $$PWD/NSLfiles/input/incl/nsl_input.h \
   $$PWD/NSLfiles/input/incl/nsl_input_include.h \
   $$PWD/NSLfiles/input/nsl_input.h \
   $$PWD/NSLfiles/kernel/incl/cmd_etc_incl/nsl_cmd_diff.h \
   $$PWD/NSLfiles/kernel/incl/cmd_etc_incl/nsl_cmd_diff_manager.h \
   $$PWD/NSLfiles/kernel/incl/cmd_etc_incl/nsl_cmd_file.h \
   $$PWD/NSLfiles/kernel/incl/cmd_etc_incl/nsl_cmd_file_manager.h \
   $$PWD/NSLfiles/kernel/incl/cmd_etc_incl/nsl_cmd_public.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_assign.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_cd.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_close.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_connect.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_cont.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_create.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_csh.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_delay.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_disable.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_elem.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_enable.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_exec.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_file_disable.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_file_enable.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_get.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_help.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_init.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_load.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_open.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_print.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_quit.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_reset.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_run.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_set.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_sh.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_status.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_step.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_stop.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_train.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_update.h \
   $$PWD/NSLfiles/kernel/incl/cmd_exec_incl/nsl_cmd_exec_write.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_buf.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_data_layer.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_function.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_int_data.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_int_matrix.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_int_vector.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_layer.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_macro.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_matrix_layer.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_model.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_module.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_num_data.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_num_matrix.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_num_vector.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_ptr_data.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_ptr_matrix.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_ptr_vector.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set_dump_type.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set_file_type.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set_int_data.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set_layer_value.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set_num_data.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set_num_matrix.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set_num_vector.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set_on_off.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set_str_data.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_set_vec_type.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_str_data.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_str_matrix.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_str_vector.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_system.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_type.h \
   $$PWD/NSLfiles/kernel/incl/cmd_main_incl/nsl_cmd_vector_layer.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_base.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_base_list.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_base_node.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_base_stack.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_buffer.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_char_buf.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_diff.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_diff_manager.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_diff_method.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_file.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_file_manager.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_interpreter.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_nsl_file.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_public.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_shell.h \
   $$PWD/NSLfiles/kernel/incl/kernel_etc_incl/nsl_streambuf.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_3_layer.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_4_layer.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_data_layer.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_dump_data.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_file_data.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_function.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_in_out_data.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_int_data.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_int_matrix.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_int_vector.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_layer.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_matrix_layer.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_model.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_module.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_0.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_1.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_2.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_3.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_4.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_dat.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_data.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_mat.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_matrix.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_vec.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_num_vector.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_on_off_data.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_ptr_data.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_ptr_matrix.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_ptr_vector.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_row_col_data.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_str_data.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_str_matrix.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_str_vector.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_sys_function.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_sys_module.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_system.h \
   $$PWD/NSLfiles/kernel/incl/kernel_main_incl/nsl_vector_layer.h \
   $$PWD/NSLfiles/kernel/incl/lib_diff_incl/nsl_diff_euler.h \
   $$PWD/NSLfiles/kernel/incl/lib_diff_incl/nsl_diff_euler_3.h \
   $$PWD/NSLfiles/kernel/incl/lib_diff_incl/nsl_diff_euler_4.h \
   $$PWD/NSLfiles/kernel/incl/lib_diff_incl/nsl_diff_euler_data.h \
   $$PWD/NSLfiles/kernel/incl/lib_diff_incl/nsl_diff_euler_matrix.h \
   $$PWD/NSLfiles/kernel/incl/lib_diff_incl/nsl_diff_euler_vector.h \
   $$PWD/NSLfiles/kernel/incl/lib_diff_incl/nsl_diff_interpolation.h \
   $$PWD/NSLfiles/kernel/incl/lib_diff_incl/nsl_diff_interpolation_data.h \
   $$PWD/NSLfiles/kernel/incl/lib_diff_incl/nsl_diff_interpolation_matrix.h \
   $$PWD/NSLfiles/kernel/incl/lib_diff_incl/nsl_diff_interpolation_vector.h \
   $$PWD/NSLfiles/kernel/incl/lib_etc_incl/nsl_buffer_stream_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_etc_incl/nsl_char_buf_stream_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_etc_incl/nsl_interpreter_stream_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_etc_incl/nsl_nsl_file_stream_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_etc_incl/nsl_stream.h \
   $$PWD/NSLfiles/kernel/incl/lib_etc_incl/nsl_streambuf_stream_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_data_add_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_data_comp_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_data_conv_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_data_div_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_data_math.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_data_max_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_data_min_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_data_mult_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_data_sub_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_mat_to_vec_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_mat_vec_prod_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_matrix_add_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_matrix_comp_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_matrix_conv_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_matrix_div_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_matrix_math.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_matrix_max_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_matrix_min_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_matrix_mult_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_matrix_sub_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_num_3_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_num_4_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_num_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_num_max_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_num_min_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_vec_to_mat_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_vector_add_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_vector_comp_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_vector_conv_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_vector_div_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_vector_math.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_vector_max_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_vector_min_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_vector_mult_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_main_incl/nsl_vector_sub_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_data_ramp_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_data_sat_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_data_sigma_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_data_step_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_matrix_expdecay_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_matrix_kernel_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_matrix_ramp_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_matrix_sat_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_matrix_sigma_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_matrix_step_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_num_ramp_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_num_sat_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_num_sigma_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_num_step_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_ramp_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_sat_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_sigma_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_step_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_thresh_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_vector_gauss_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_vector_ramp_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_vector_sat_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_vector_sigma_library.h \
   $$PWD/NSLfiles/kernel/incl/lib_thresh_incl/nsl_vector_step_library.h \
   $$PWD/NSLfiles/kernel/incl/nsl.h \
   $$PWD/NSLfiles/kernel/incl/nsl_all_kernel_include.h \
   $$PWD/NSLfiles/kernel/incl/nsl_command_include.h \
   $$PWD/NSLfiles/kernel/incl/nsl_data_math.h \
   $$PWD/NSLfiles/kernel/incl/nsl_kernel_include.h \
   $$PWD/NSLfiles/kernel/incl/nsl_library_include.h \
   $$PWD/NSLfiles/kernel/incl/nsl_matrix_math.h \
   $$PWD/NSLfiles/kernel/incl/nsl_num.h \
   $$PWD/NSLfiles/kernel/incl/nsl_num_decl.h \
   $$PWD/NSLfiles/kernel/incl/nsl_other_include.h \
   $$PWD/NSLfiles/kernel/incl/nsl_stream.h \
   $$PWD/NSLfiles/kernel/incl/nsl_vector_math.h \
#   $$PWD/NSLfiles/kernel/nsl_kernel.h \
   $$PWD/NSLfiles/kernel/nsl_num_decl.h \
   $$PWD/NSLfiles/MAIN/incl/nsl_include.h \
   $$PWD/NSLfiles/MAIN/src/sys_main_src/nsl2.h \
   $$PWD/NSLfiles/MAIN/src/sys_main_src/nsl_all_kernel_include.h \
   $$PWD/NSLfiles/MAIN/src/sys_main_src/nsl_command_include.h \
   $$PWD/NSLfiles/MAIN/src/sys_main_src/nsl_kernel_include.h \
   $$PWD/NSLfiles/MAIN/src/sys_main_src/nsl_library_include.h \
   $$PWD/NSLfiles/MAIN/src/sys_main_src/nsl_other_include.h \
   $$PWD/NSLfiles/MaxSelector/maxSelector.h \
   $$PWD/NSLfiles/rts/incl/asl.h \
   $$PWD/NSLfiles/rts/incl/asl_all_rts_include.h \
   $$PWD/NSLfiles/rts/incl/asl_seq.h \
   $$PWD/NSLfiles/rts/incl/aslcom_seq.h \
   $$PWD/NSLfiles/rts/incl/aslio.h \
   $$PWD/NSLfiles/rts/incl/asllist.h \
   $$PWD/NSLfiles/rts/incl/nsl_din_num_0.h \
   $$PWD/NSLfiles/rts/incl/nsl_din_num_1.h \
   $$PWD/NSLfiles/rts/incl/nsl_din_num_2.h \
   $$PWD/NSLfiles/rts/incl/nsl_din_num_3.h \
   $$PWD/NSLfiles/rts/incl/nsl_din_num_4.h \
   $$PWD/NSLfiles/rts/incl/nsl_dout_num_0.h \
   $$PWD/NSLfiles/rts/incl/nsl_dout_num_1.h \
   $$PWD/NSLfiles/rts/incl/nsl_dout_num_2.h \
   $$PWD/NSLfiles/rts/incl/nsl_dout_num_3.h \
   $$PWD/NSLfiles/rts/incl/nsl_dout_num_4.h \
   $$PWD/NSLfiles/xkernel/incl/tmp/sun_winds.h \
   $$PWD/NSLfiles/xkernel/incl/tmp/xnsl_command.h \
   $$PWD/NSLfiles/xkernel/incl/tmp/xnsl_winds.h \
   $$PWD/NSLfiles/xkernel/incl/tmp/xview_winds.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_3.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_4.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_area_level.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_area_level_3.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_area_level_4.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_area_level_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_area_level_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_area_level_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_spatial_2.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_spatial_2_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_spatial_2_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_spatial_2_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_spatial_3.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_spatial_3_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_spatial_3_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_spatial_3_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_temporal.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_temporal_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_temporal_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_temporal_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_canvas_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_frame.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_area_level.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_area_level_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_area_level_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_area_level_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_spatial_2.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_spatial_2_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_spatial_2_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_spatial_2_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_spatial_3.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_spatial_3_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_spatial_3_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_spatial_3_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_temporal.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_temporal_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_temporal_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_temporal_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_panel_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_3.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_4.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_area_level.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_area_level_3.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_area_level_4.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_area_level_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_area_level_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_area_level_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_spatial_2.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_spatial_2_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_spatial_2_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_spatial_2_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_spatial_3.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_spatial_3_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_spatial_3_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_spatial_3_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_temporal.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_temporal_data.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_temporal_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_temporal_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_display_window_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_system.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_window.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_cmd_window_interface.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_command_buffer.h \
   $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl/xnsl_commands.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_etc_incl/xnsl_etc_include.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_etc_incl/xnsl_lib_widget.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_etc_incl/xnsl_manager.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_etc_incl/xnsl_widget.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_etc_incl/xnsl_xpublic.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_area_level_graph.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_area_level_graph_data.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_area_level_graph_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_area_level_graph_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_graph_include.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_spatial_graph_2.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_spatial_graph_2_data.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_spatial_graph_2_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_spatial_graph_2_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_spatial_graph_3.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_spatial_graph_3_data.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_spatial_graph_3_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_spatial_graph_3_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_temporal_graph.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_temporal_graph_data.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_temporal_graph_matrix.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_temporal_graph_vector.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl/xnsl_topology_graph_2.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_main_incl/xnsl_display_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_main_incl/xnsl_display_frame.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_main_incl/xnsl_display_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_main_incl/xnsl_display_window.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_main_incl/xnsl_system.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_main_incl/xnsl_window.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_main_incl/xnsl_window_interface.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_application.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_callback.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_canvas_item.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_cmd_message.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_frame.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_graph.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_grid.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_line.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_menu.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_panel_item.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_pic_button.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_push_button.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_scrollable_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_scrollable_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_text_label_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_text_label_input.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_text_label_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_text_menu_button.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_widget_graph.h \
   $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl/xnsl_widget_include.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_application.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_callback.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_canvas_functions.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_canvas_item.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_cmd_message.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_frame.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_include.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_menu.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_motif_include.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_panel_item.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_pic_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_push_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_scrollable_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_scrollable_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_text_label_input.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_text_label_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_text_menu_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl/xnsl_motif_widget.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xlib_qt_controls_incl/xlib_qt_canvascontrol.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xlib_qt_controls_incl/xlib_qt_control.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xlib_qt_controls_incl/xlib_qt_framecontrol.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xlib_qt_controls_incl/xlib_qt_interface.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_application.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_canvas_item.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_cmd_message.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_frame.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_graph.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_include.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_menu.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_panel_item.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_pic_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_push_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_text_label_input.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_text_menu_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xnsl_qt_widget.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_application.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_callback.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_canvas_item.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_cmd_message.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_frame.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_graph.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_include.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_menu.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_panel_item.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_pic_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_push_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_scrollable_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_scrollable_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_tcltk_include.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_text_label_input.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_text_label_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_text_menu_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl/xnsl_tcltk_widget.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xlib_incl/xnsl_xlib_graph.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xlib_incl/xnsl_xlib_include.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xlib_incl/xnsl_xlib_widget.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_application.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_callback.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_canvas_functions.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_canvas_item.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_cmd_message.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_frame.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_include.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_menu.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_panel_item.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_pic_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_push_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_scrollable_canvas.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_scrollable_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_text_label_input.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_text_label_panel.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_text_menu_button.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_widget.h \
   $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl/xnsl_xview_xview_include.h \
   $$PWD/NSLfiles/xkernel/incl/xnsl.h \
   $$PWD/NSLfiles/xkernel/incl/xnsl_all_xkernel_include.h \
   $$PWD/NSLfiles/xkernel/incl/xnsl_command_include.h \
   $$PWD/NSLfiles/xkernel/incl/xnsl_other_include.h \
   $$PWD/NSLfiles/xkernel/incl/xnsl_xkernel_include.h \
   $$PWD/NSLfiles/xkernel/src/xkernel.h \
   $$PWD/NSLfiles/nsl_kernel.h \
   $$PWD/QtCustomPlot/qcustomplot.h

SOURCES = \
   $$PWD/NSLControls/src/NSLMainWindow.cpp \
   $$PWD/NSLControls/src/NSLVectorGraph.cpp \
   $$PWD/NSLControls/QtNSLCore.cpp \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_block_stim.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_block_stim_data.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_block_stim_matrix.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_block_stim_vector.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_icon_stim.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_icon_stim_data.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_icon_stim_matrix.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_icon_stim_vector.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_input_data.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_input_layer.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_input_matrix.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_input_stim.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_input_vector.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_spec_type.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_stim.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_stim_data.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_stim_matrix.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_stim_type.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_stim_vector.C \
   $$PWD/NSLfiles/input/src/cmd_stim_src/nsl_cmd_time_interval.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_block_stim_data.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_block_stim_matrix.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_block_stim_vector.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_icon_stim_data.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_icon_stim_matrix.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_icon_stim_vector.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_input_data.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_input_layer.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_input_matrix.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_input_vector.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_stim.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_stim_data.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_stim_matrix.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_stim_vector.C \
   $$PWD/NSLfiles/input/src/input_stim_src/nsl_time_interval.C \
   $$PWD/NSLfiles/input/src/main_src/nsl_input_main.C \
   $$PWD/NSLfiles/kernel/src/cmd_etc_src/nsl_cmd_diff.C \
   $$PWD/NSLfiles/kernel/src/cmd_etc_src/nsl_cmd_diff_manager.C \
   $$PWD/NSLfiles/kernel/src/cmd_etc_src/nsl_cmd_file.C \
   $$PWD/NSLfiles/kernel/src/cmd_etc_src/nsl_cmd_file_manager.C \
   $$PWD/NSLfiles/kernel/src/cmd_etc_src/nsl_cmd_public.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_assign.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_cd.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_close.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_connect.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_cont.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_create.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_csh.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_delay.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_disable.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_elem.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_enable.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_exec.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_file_disable.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_file_enable.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_get.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_help.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_init.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_load.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_open.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_print.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_quit.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_reset.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_run.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_set.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_sh.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_status.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_step.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_stop.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_train.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_update.C \
   $$PWD/NSLfiles/kernel/src/cmd_exec_src/nsl_cmd_exec_write.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_buf.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_data_layer.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_function.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_int_data.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_int_matrix.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_int_vector.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_layer.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_macro.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_matrix_layer.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_model.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_module.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_num_data.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_num_matrix.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_num_vector.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_ptr_data.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_ptr_matrix.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_ptr_vector.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_str_data.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_str_matrix.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_str_vector.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_system.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_type.C \
   $$PWD/NSLfiles/kernel/src/cmd_main_src/nsl_cmd_vector_layer.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_base.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_base_list.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_base_node.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_base_stack.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_buffer.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_char_buf.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_diff.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_diff_manager.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_diff_method.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_error.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_file.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_file_manager.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_general.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_handlers.c \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_interpreter.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_nsl_file.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_public.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_shell.C \
   $$PWD/NSLfiles/kernel/src/kernel_etc_src/nsl_streambuf.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_3_layer.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_4_layer.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_data_layer.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_dump_data.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_file_data.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_function.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_in_out_data.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_int_data.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_int_matrix.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_int_vector.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_layer.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_matrix_layer.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_model.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_module.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_num_0.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_num_1.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_num_2.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_num_3.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_num_4.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_num_data.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_num_matrix.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_num_vector.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_on_off_data.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_ptr_data.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_ptr_matrix.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_ptr_vector.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_row_col_data.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_str_data.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_str_matrix.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_str_vector.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_sys_function.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_sys_module.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_system.C \
   $$PWD/NSLfiles/kernel/src/kernel_main_src/nsl_vector_layer.C \
   $$PWD/NSLfiles/kernel/src/lib_diff_src/nsl_diff_euler.C \
   $$PWD/NSLfiles/kernel/src/lib_diff_src/nsl_diff_euler_3.C \
   $$PWD/NSLfiles/kernel/src/lib_diff_src/nsl_diff_euler_4.C \
   $$PWD/NSLfiles/kernel/src/lib_diff_src/nsl_diff_euler_data.C \
   $$PWD/NSLfiles/kernel/src/lib_diff_src/nsl_diff_euler_matrix.C \
   $$PWD/NSLfiles/kernel/src/lib_diff_src/nsl_diff_euler_vector.C \
   $$PWD/NSLfiles/kernel/src/lib_diff_src/nsl_diff_interpolation.C \
   $$PWD/NSLfiles/kernel/src/lib_diff_src/nsl_diff_interpolation_data.C \
   $$PWD/NSLfiles/kernel/src/lib_diff_src/nsl_diff_interpolation_matrix.C \
   $$PWD/NSLfiles/kernel/src/lib_diff_src/nsl_diff_interpolation_vector.C \
   $$PWD/NSLfiles/kernel/src/lib_etc_src/nsl_buffer_stream_library.C \
   $$PWD/NSLfiles/kernel/src/lib_etc_src/nsl_char_buf_stream_library.C \
   $$PWD/NSLfiles/kernel/src/lib_etc_src/nsl_interpreter_stream_library.C \
   $$PWD/NSLfiles/kernel/src/lib_etc_src/nsl_nsl_file_stream_library.C \
   $$PWD/NSLfiles/kernel/src/lib_etc_src/nsl_streambuf_stream_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_data_add_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_data_comp_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_data_conv_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_data_div_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_data_max_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_data_min_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_data_mult_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_data_sub_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_mat_to_vec_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_mat_vec_prod_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_matrix_add_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_matrix_comp_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_matrix_conv_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_matrix_div_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_matrix_max_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_matrix_min_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_matrix_mult_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_matrix_sub_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_num_3_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_num_4_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_num_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_num_max_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_num_min_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_vec_to_mat_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_vector_add_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_vector_comp_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_vector_conv_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_vector_div_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_vector_max_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_vector_min_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_vector_mult_library.C \
   $$PWD/NSLfiles/kernel/src/lib_main_src/nsl_vector_sub_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_data_ramp_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_data_sat_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_data_sigma_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_data_step_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_matrix_expdecay_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_matrix_kernel_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_matrix_ramp_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_matrix_sat_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_matrix_sigma_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_matrix_step_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_num_ramp_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_num_sat_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_num_sigma_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_num_step_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_ramp_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_sat_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_sigma_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_step_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_thresh_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_vector_gauss_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_vector_ramp_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_vector_sat_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_vector_sigma_library.C \
   $$PWD/NSLfiles/kernel/src/lib_thresh_src/nsl_vector_step_library.C \
   $$PWD/NSLfiles/kernel/src/main_src/nsl_kernel_main_short.C \
   $$PWD/NSLfiles/MAIN/src/sys_main_src/asl_sys_main.C \
   $$PWD/NSLfiles/MAIN/src/sys_main_src/nsl_sys_etc.cpp \
   $$PWD/NSLfiles/MAIN/src/sys_main_src/nsl_sys_main.cpp \
   $$PWD/NSLfiles/MAIN/src/sys_main_src/xnsl_sys_xmain.cpp \
   $$PWD/NSLfiles/MaxSelector/maxSelector.C \
   $$PWD/NSLfiles/rts/src/aslcom_seq.C \
   $$PWD/NSLfiles/rts/src/aslio.C \
   $$PWD/NSLfiles/rts/src/aslrts_seq.C \
   $$PWD/NSLfiles/rts/src/nsl_din_num_0.C \
   $$PWD/NSLfiles/rts/src/nsl_din_num_1.C \
   $$PWD/NSLfiles/rts/src/nsl_din_num_2.C \
   $$PWD/NSLfiles/rts/src/nsl_din_num_3.C \
   $$PWD/NSLfiles/rts/src/nsl_din_num_4.C \
   $$PWD/NSLfiles/rts/src/nsl_dout_num_0.C \
   $$PWD/NSLfiles/rts/src/nsl_dout_num_1.C \
   $$PWD/NSLfiles/rts/src/nsl_dout_num_2.C \
   $$PWD/NSLfiles/rts/src/nsl_dout_num_3.C \
   $$PWD/NSLfiles/rts/src/nsl_dout_num_4.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_3.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_4.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_area_level.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_area_level_3.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_area_level_4.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_area_level_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_area_level_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_area_level_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_spatial_2.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_spatial_2_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_spatial_2_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_spatial_2_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_spatial_3.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_spatial_3_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_spatial_3_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_spatial_3_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_temporal.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_temporal_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_temporal_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_temporal_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_canvas_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_frame.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_area_level.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_area_level_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_area_level_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_area_level_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_spatial_2.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_spatial_2_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_spatial_2_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_spatial_2_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_spatial_3.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_spatial_3_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_spatial_3_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_spatial_3_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_temporal.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_temporal_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_temporal_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_temporal_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_panel_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_3.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_4.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_area_level.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_area_level_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_area_level_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_area_level_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_spatial_2.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_spatial_2_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_spatial_2_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_spatial_2_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_spatial_3.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_spatial_3_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_spatial_3_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_spatial_3_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_temporal.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_temporal_data.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_temporal_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_temporal_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_display_window_vector.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_system.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_window.C \
   $$PWD/NSLfiles/xkernel/src/xcmd_main_src/xnsl_cmd_window_interface.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_etc_src/xnsl_lib_widget.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_etc_src/xnsl_manager.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_etc_src/xnsl_widget.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_etc_src/xnsl_xpublic.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_area_level_graph.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_area_level_graph_data.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_area_level_graph_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_area_level_graph_vector.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_graph_3d.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_graph_main.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_graphics_library.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_spatial_graph_2.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_spatial_graph_2_data.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_spatial_graph_2_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_spatial_graph_2_vector.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_spatial_graph_3.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_spatial_graph_3_data.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_spatial_graph_3_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_spatial_graph_3_vector.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_temporal_graph.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_temporal_graph_data.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_temporal_graph_matrix.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_temporal_graph_vector.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_topol_graph.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_graph_src/xnsl_topology_graph_2.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_main_src/xnsl_display_canvas.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_main_src/xnsl_display_frame.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_main_src/xnsl_display_panel.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_main_src/xnsl_display_window.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_main_src/xnsl_system.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_main_src/xnsl_window.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_main_src/xnsl_window_interface.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_application.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_callback.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_canvas.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_canvas_item.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_cmd_message.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_frame.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_graph.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_grid.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_line.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_menu.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_panel.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_panel_item.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_pic_button.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_push_button.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_scrollable_canvas.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_scrollable_panel.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_text_label_canvas.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_text_label_input.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_text_label_panel.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_text_menu_button.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_widget_graph.C \
   $$PWD/NSLfiles/xkernel/src/xkernel_widget_src/xnsl_widget_main.C \
   $$PWD/NSLfiles/xkernel/src/xlib_motif_src/xnsl_motif_main.C \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xlib_qt_controls_src/xlib_qt_canvascontrol.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xlib_qt_controls_src/xlib_qt_control.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xlib_qt_controls_src/xlib_qt_framecontrol.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xlib_qt_controls_src/xlib_qt_interface.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_application.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_canvas.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_canvas_item.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_cmd_message.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_frame.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_graph.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_main.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_menu.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_panel.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_panel_item.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_pic_button.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_push_button.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_text_label_input.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_text_menu_button.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_qt_src/xnsl_qt_widget.cpp \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_application.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_callback.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_canvas.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_canvas_item.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_cmd_message.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_frame.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_graph.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_main.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_menu.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_panel.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_panel_item.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_pic_button.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_push_button.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_scrollable_canvas.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_scrollable_panel.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_text_label_input.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_text_label_panel.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_text_menu_button.C \
   $$PWD/NSLfiles/xkernel/src/xlib_tcltk_src/xnsl_tcltk_widget.C \
   $$PWD/NSLfiles/xkernel/src/xlib_xlib_src/xnsl_xlib_graph.C \
   $$PWD/NSLfiles/xkernel/src/xlib_xlib_src/xnsl_xlib_main.C \
   $$PWD/NSLfiles/xkernel/src/xlib_xlib_src/xnsl_xlib_widget.C \
   $$PWD/NSLfiles/xkernel/src/xmain_src/xnsl_xkernel_main_short.C \
   $$PWD/QtCustomPlot/qcustomplot.cpp \
   $$PWD/qtnsl.cpp

INCLUDEPATH = \
    $$PWD/NSLControls/incl \
    $$PWD/NSLfiles \
    $$PWD/NSLfiles/input \
    $$PWD/NSLfiles/input/incl \
    $$PWD/NSLfiles/input/incl/cmd_stim_incl \
    $$PWD/NSLfiles/input/incl/input_stim_incl \
    $$PWD/NSLfiles/kernel \
    $$PWD/NSLfiles/kernel/incl \
    $$PWD/NSLfiles/kernel/incl/cmd_etc_incl \
    $$PWD/NSLfiles/kernel/incl/cmd_exec_incl \
    $$PWD/NSLfiles/kernel/incl/cmd_main_incl \
    $$PWD/NSLfiles/kernel/incl/kernel_etc_incl \
    $$PWD/NSLfiles/kernel/incl/kernel_main_incl \
    $$PWD/NSLfiles/kernel/incl/lib_diff_incl \
    $$PWD/NSLfiles/kernel/incl/lib_etc_incl \
    $$PWD/NSLfiles/kernel/incl/lib_main_incl \
    $$PWD/NSLfiles/kernel/incl/lib_thresh_incl \
    $$PWD/NSLfiles/MAIN/incl \
    $$PWD/NSLfiles/MAIN/src/sys_main_src \
    $$PWD/NSLfiles/MaxSelector \
    $$PWD/NSLfiles/rts/incl \
    $$PWD/NSLfiles/xkernel/incl \
    $$PWD/NSLfiles/xkernel/incl/tmp \
    $$PWD/NSLfiles/xkernel/incl/xcmd_main_incl \
    $$PWD/NSLfiles/xkernel/incl/xkernel_etc_incl \
    $$PWD/NSLfiles/xkernel/incl/xkernel_graph_incl \
    $$PWD/NSLfiles/xkernel/incl/xkernel_main_incl \
    $$PWD/NSLfiles/xkernel/incl/xkernel_widget_incl \
    $$PWD/NSLfiles/xkernel/incl/xlib_motif_incl \
    $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl \
    $$PWD/NSLfiles/xkernel/incl/xlib_qt_incl/xlib_qt_controls_incl \
    $$PWD/NSLfiles/xkernel/incl/xlib_tcltk_incl \
    $$PWD/NSLfiles/xkernel/incl/xlib_xlib_incl \
    $$PWD/NSLfiles/xkernel/incl/xlib_xview_incl \
    $$PWD/NSLfiles/xkernel/src \
    $$PWD/QtCustomPlot

#DEFINES = 

win32{

    # USE windeployqt to deploy the application to the destination folder

    ADD_QT_BIN_PATH = set PATH=$$shell_quote($$shell_path($$[QT_INSTALL_BINS]));%PATH%
    DEPLOY_TARGET = $$shell_quote($$shell_path($${DESTDIR}/qtnsl.exe))
    DEPLOY_COMMAND = $$ADD_QT_BIN_PATH && $$shell_quote($$shell_path(windeployqt))
    warning($${DEPLOY_COMMAND} $${DEPLOY_TARGET})
    QMAKE_POST_LINK = $${DEPLOY_COMMAND} $${DEPLOY_TARGET}

}
