/* SCCS  @(#)xnsl_command_include.h	1.6---97/12/09--19:22:05 */
/****************************************************************/
/*                                                              */
/*                       xnsl_command_include.h                 */
/*                                                              */
/****************************************************************/

# include "xcmd_main_incl/xnsl_cmd_window.h"

# include "xcmd_main_incl/xnsl_cmd_display_window.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_3.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_4.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_area_level.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_area_level_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_area_level_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_area_level_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_area_level_3.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_area_level_4.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_spatial_2.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_spatial_2_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_spatial_2_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_spatial_2_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_spatial_3.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_spatial_3_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_spatial_3_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_spatial_3_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_temporal.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_temporal_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_temporal_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_window_temporal_matrix.h"

# include "xcmd_main_incl/xnsl_cmd_display_frame.h"

# include "xcmd_main_incl/xnsl_cmd_display_canvas.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_3.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_4.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_area_level.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_area_level_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_area_level_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_area_level_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_area_level_3.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_area_level_4.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_spatial_2.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_spatial_2_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_spatial_2_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_spatial_2_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_spatial_3.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_spatial_3_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_spatial_3_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_spatial_3_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_temporal.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_temporal_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_temporal_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_canvas_temporal_matrix.h"

# include "xcmd_main_incl/xnsl_cmd_display_panel.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_area_level.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_area_level_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_area_level_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_area_level_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_spatial_2.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_spatial_2_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_spatial_2_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_spatial_2_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_spatial_3.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_spatial_3_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_spatial_3_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_spatial_3_matrix.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_temporal.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_temporal_data.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_temporal_vector.h"
# include "xcmd_main_incl/xnsl_cmd_display_panel_temporal_matrix.h"

# include "xcmd_main_incl/xnsl_cmd_window_interface.h"
# include "xcmd_main_incl/xnsl_cmd_system.h"

